//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearVR_Controller {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UP ARROW")]
        public string touchTopButton {
            get {
                return ((string)(this["touchTopButton"]));
            }
            set {
                this["touchTopButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RIGHT ARROW")]
        public string touchRightButton {
            get {
                return ((string)(this["touchRightButton"]));
            }
            set {
                this["touchRightButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOWN ARROW")]
        public string touchBotButton {
            get {
                return ((string)(this["touchBotButton"]));
            }
            set {
                this["touchBotButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEFT ARROW")]
        public string touchLeftButton {
            get {
                return ((string)(this["touchLeftButton"]));
            }
            set {
                this["touchLeftButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Toggle")]
        public string touchMidButton {
            get {
                return ((string)(this["touchMidButton"]));
            }
            set {
                this["touchMidButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UP ARROW")]
        public string triggerTopButton {
            get {
                return ((string)(this["triggerTopButton"]));
            }
            set {
                this["triggerTopButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RIGHT ARROW")]
        public string triggerRightButton {
            get {
                return ((string)(this["triggerRightButton"]));
            }
            set {
                this["triggerRightButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOWN ARROW")]
        public string triggerBotButton {
            get {
                return ((string)(this["triggerBotButton"]));
            }
            set {
                this["triggerBotButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEFT ARROW")]
        public string triggerLeftButton {
            get {
                return ((string)(this["triggerLeftButton"]));
            }
            set {
                this["triggerLeftButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Toggle")]
        public string triggerMidButton {
            get {
                return ((string)(this["triggerMidButton"]));
            }
            set {
                this["triggerMidButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left mouse button")]
        public string triggerButton {
            get {
                return ((string)(this["triggerButton"]));
            }
            set {
                this["triggerButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Browser Back")]
        public string backButton {
            get {
                return ((string)(this["backButton"]));
            }
            set {
                this["backButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Volume Up")]
        public string volumeUpButton {
            get {
                return ((string)(this["volumeUpButton"]));
            }
            set {
                this["volumeUpButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Volume Down")]
        public string volumeDownButton {
            get {
                return ((string)(this["volumeDownButton"]));
            }
            set {
                this["volumeDownButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F6:FA:0F:BA:BA:2C")]
        public string macAddressText {
            get {
                return ((string)(this["macAddressText"]));
            }
            set {
                this["macAddressText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Axis {
            get {
                return ((bool)(this["Axis"]));
            }
            set {
                this["Axis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Gyro {
            get {
                return ((bool)(this["Gyro"]));
            }
            set {
                this["Gyro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Magnet {
            get {
                return ((bool)(this["Magnet"]));
            }
            set {
                this["Magnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Accel {
            get {
                return ((bool)(this["Accel"]));
            }
            set {
                this["Accel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string currentButton {
            get {
                return ((string)(this["currentButton"]));
            }
            set {
                this["currentButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Browser Home")]
        public string homeButton {
            get {
                return ((string)(this["homeButton"]));
            }
            set {
                this["homeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _triggerButton {
            get {
                return ((bool)(this["_triggerButton"]));
            }
            set {
                this["_triggerButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _homeButton {
            get {
                return ((bool)(this["_homeButton"]));
            }
            set {
                this["_homeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _backButton {
            get {
                return ((bool)(this["_backButton"]));
            }
            set {
                this["_backButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _touchpadButton {
            get {
                return ((bool)(this["_touchpadButton"]));
            }
            set {
                this["_touchpadButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _volumeUpButton {
            get {
                return ((bool)(this["_volumeUpButton"]));
            }
            set {
                this["_volumeUpButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _volumeDownButton {
            get {
                return ((bool)(this["_volumeDownButton"]));
            }
            set {
                this["_volumeDownButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _NoButton {
            get {
                return ((bool)(this["_NoButton"]));
            }
            set {
                this["_NoButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _touchpadButton_latch {
            get {
                return ((bool)(this["_touchpadButton_latch"]));
            }
            set {
                this["_touchpadButton_latch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _triggerButton_latch {
            get {
                return ((bool)(this["_triggerButton_latch"]));
            }
            set {
                this["_triggerButton_latch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _useWheel {
            get {
                return ((bool)(this["_useWheel"]));
            }
            set {
                this["_useWheel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _useTouch {
            get {
                return ((bool)(this["_useTouch"]));
            }
            set {
                this["_useTouch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _reset {
            get {
                return ((bool)(this["_reset"]));
            }
            set {
                this["_reset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _volbtn {
            get {
                return ((bool)(this["_volbtn"]));
            }
            set {
                this["_volbtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _tchbtn {
            get {
                return ((bool)(this["_tchbtn"]));
            }
            set {
                this["_tchbtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _trig {
            get {
                return ((bool)(this["_trig"]));
            }
            set {
                this["_trig"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int _numberOfWheelPositions {
            get {
                return ((int)(this["_numberOfWheelPositions"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int scrollWheel {
            get {
                return ((int)(this["scrollWheel"]));
            }
            set {
                this["scrollWheel"] = value;
            }
        }
    }
}
