//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearVR_Controller {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class User : global::System.Configuration.ApplicationSettingsBase {
        
        private static User defaultInstance = ((User)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new User())));
        
        public static User Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UP ARROW")]
        public string TouchTopButton {
            get {
                return ((string)(this["TouchTopButton"]));
            }
            set {
                this["TouchTopButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RIGHT ARROW")]
        public string TouchRightButton {
            get {
                return ((string)(this["TouchRightButton"]));
            }
            set {
                this["TouchRightButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOWN ARROW")]
        public string TouchBotButton {
            get {
                return ((string)(this["TouchBotButton"]));
            }
            set {
                this["TouchBotButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEFT ARROW")]
        public string TouchLeftButton {
            get {
                return ((string)(this["TouchLeftButton"]));
            }
            set {
                this["TouchLeftButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Toggle")]
        public string TouchMidButton {
            get {
                return ((string)(this["TouchMidButton"]));
            }
            set {
                this["TouchMidButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UP ARROW")]
        public string TriggerTopButton {
            get {
                return ((string)(this["TriggerTopButton"]));
            }
            set {
                this["TriggerTopButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RIGHT ARROW")]
        public string TriggerRightButton {
            get {
                return ((string)(this["TriggerRightButton"]));
            }
            set {
                this["TriggerRightButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOWN ARROW")]
        public string TriggerBotButton {
            get {
                return ((string)(this["TriggerBotButton"]));
            }
            set {
                this["TriggerBotButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEFT ARROW")]
        public string TriggerLeftButton {
            get {
                return ((string)(this["TriggerLeftButton"]));
            }
            set {
                this["TriggerLeftButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Toggle")]
        public string TriggerMidButton {
            get {
                return ((string)(this["TriggerMidButton"]));
            }
            set {
                this["TriggerMidButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mouse left button")]
        public string TriggerButton {
            get {
                return ((string)(this["TriggerButton"]));
            }
            set {
                this["TriggerButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Browser Back")]
        public string BackButton {
            get {
                return ((string)(this["BackButton"]));
            }
            set {
                this["BackButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Volume Up")]
        public string VolumeUpButton {
            get {
                return ((string)(this["VolumeUpButton"]));
            }
            set {
                this["VolumeUpButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Volume Down")]
        public string VolumeDownButton {
            get {
                return ((string)(this["VolumeDownButton"]));
            }
            set {
                this["VolumeDownButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F6:FA:0F:BA:BA:2C")]
        public string MACAddressText {
            get {
                return ((string)(this["MACAddressText"]));
            }
            set {
                this["MACAddressText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Axis {
            get {
                return ((bool)(this["Axis"]));
            }
            set {
                this["Axis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Gyro {
            get {
                return ((bool)(this["Gyro"]));
            }
            set {
                this["Gyro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Magnet {
            get {
                return ((bool)(this["Magnet"]));
            }
            set {
                this["Magnet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Accel {
            get {
                return ((bool)(this["Accel"]));
            }
            set {
                this["Accel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Browser Start and Home")]
        public string HomeButton {
            get {
                return ((string)(this["HomeButton"]));
            }
            set {
                this["HomeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ScrollWheelSeg {
            get {
                return ((int)(this["ScrollWheelSeg"]));
            }
            set {
                this["ScrollWheelSeg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int ScrollWheelSpeed {
            get {
                return ((int)(this["ScrollWheelSpeed"]));
            }
            set {
                this["ScrollWheelSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnect {
            get {
                return ((bool)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
    }
}
